# Generated by Django 5.2.1 on 2025-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
