# Generated by Django 5.2.1 on 2025-05-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='studentname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
