# Generated by Django 5.2.1 on 2025-05-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umaapp', '0002_alter_biodata_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='phoneno',
            field=models.CharField(max_length=20),
        ),
    ]
